dataset:
  voc_root: VOCdevkit
  train_txt: VOC2007/ImageSets/Segmentation/train.txt
  val_txt: VOC2007/ImageSets/Segmentation/val.txt
  image_dir: VOC2007/JPEGImages
  mask_dir: VOC2007/SegmentationClass

  # 原仓库 input_shape 是 [H, W]
  input_shape: [512, 512]

  # 如果你的 mask 像素是 0/255，且 255 表示前景，就设 true
  # 如果你的 mask 已经是 0/1，就设 false
  mask_255_to_1: true

model:
  phi: b0
  num_classes: 2
  class_names: [background, capybara]
  pretrained: false
  model_path: ""

train:
  seed: 11
  cuda: true
  distributed: false
  sync_bn: false
  epochs: 1
  batch_size: 2
  lr: 0.0001
  min_lr_ratio: 0.01
  lr_decay_type: cos
  weight_decay: 0.01
  num_workers: 0
  save_dir: outputs/checkpoints
  save_period: 5

predict:
  model_path: outputs/checkpoints/best_epoch_weights.pth
  output_dir: outputs/predict

eval:
  # 0: generate predictions and compute metrics; 1: generate only; 2: compute only
  miou_mode: 0
  model_path: outputs/checkpoints/best_epoch_weights.pth
  output_dir: outputs/eval
  pred_dir: detection-results
